# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.9
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_TaylorPLib', [dirname(__file__)])
        except ImportError:
            import _TaylorPLib
            return _TaylorPLib
        if fp is not None:
            try:
                _mod = imp.load_module('_TaylorPLib', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _TaylorPLib = swig_import_helper()
    del swig_import_helper
else:
    import _TaylorPLib
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _TaylorPLib.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self): return _TaylorPLib.SwigPyIterator_value(self)
    def incr(self, n=1): return _TaylorPLib.SwigPyIterator_incr(self, n)
    def decr(self, n=1): return _TaylorPLib.SwigPyIterator_decr(self, n)
    def distance(self, *args): return _TaylorPLib.SwigPyIterator_distance(self, *args)
    def equal(self, *args): return _TaylorPLib.SwigPyIterator_equal(self, *args)
    def copy(self): return _TaylorPLib.SwigPyIterator_copy(self)
    def next(self): return _TaylorPLib.SwigPyIterator_next(self)
    def __next__(self): return _TaylorPLib.SwigPyIterator___next__(self)
    def previous(self): return _TaylorPLib.SwigPyIterator_previous(self)
    def advance(self, *args): return _TaylorPLib.SwigPyIterator_advance(self, *args)
    def __eq__(self, *args): return _TaylorPLib.SwigPyIterator___eq__(self, *args)
    def __ne__(self, *args): return _TaylorPLib.SwigPyIterator___ne__(self, *args)
    def __iadd__(self, *args): return _TaylorPLib.SwigPyIterator___iadd__(self, *args)
    def __isub__(self, *args): return _TaylorPLib.SwigPyIterator___isub__(self, *args)
    def __add__(self, *args): return _TaylorPLib.SwigPyIterator___add__(self, *args)
    def __sub__(self, *args): return _TaylorPLib.SwigPyIterator___sub__(self, *args)
    def __iter__(self): return self
SwigPyIterator_swigregister = _TaylorPLib.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class Line(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Line, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Line, name)
    __repr__ = _swig_repr
    def iterator(self): return _TaylorPLib.Line_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _TaylorPLib.Line___nonzero__(self)
    def __bool__(self): return _TaylorPLib.Line___bool__(self)
    def __len__(self): return _TaylorPLib.Line___len__(self)
    def pop(self): return _TaylorPLib.Line_pop(self)
    def __getslice__(self, *args): return _TaylorPLib.Line___getslice__(self, *args)
    def __setslice__(self, *args): return _TaylorPLib.Line___setslice__(self, *args)
    def __delslice__(self, *args): return _TaylorPLib.Line___delslice__(self, *args)
    def __delitem__(self, *args): return _TaylorPLib.Line___delitem__(self, *args)
    def __getitem__(self, *args): return _TaylorPLib.Line___getitem__(self, *args)
    def __setitem__(self, *args): return _TaylorPLib.Line___setitem__(self, *args)
    def append(self, *args): return _TaylorPLib.Line_append(self, *args)
    def empty(self): return _TaylorPLib.Line_empty(self)
    def size(self): return _TaylorPLib.Line_size(self)
    def clear(self): return _TaylorPLib.Line_clear(self)
    def swap(self, *args): return _TaylorPLib.Line_swap(self, *args)
    def get_allocator(self): return _TaylorPLib.Line_get_allocator(self)
    def begin(self): return _TaylorPLib.Line_begin(self)
    def end(self): return _TaylorPLib.Line_end(self)
    def rbegin(self): return _TaylorPLib.Line_rbegin(self)
    def rend(self): return _TaylorPLib.Line_rend(self)
    def pop_back(self): return _TaylorPLib.Line_pop_back(self)
    def erase(self, *args): return _TaylorPLib.Line_erase(self, *args)
    def __init__(self, *args): 
        this = _TaylorPLib.new_Line(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _TaylorPLib.Line_push_back(self, *args)
    def front(self): return _TaylorPLib.Line_front(self)
    def back(self): return _TaylorPLib.Line_back(self)
    def assign(self, *args): return _TaylorPLib.Line_assign(self, *args)
    def resize(self, *args): return _TaylorPLib.Line_resize(self, *args)
    def insert(self, *args): return _TaylorPLib.Line_insert(self, *args)
    def reserve(self, *args): return _TaylorPLib.Line_reserve(self, *args)
    def capacity(self): return _TaylorPLib.Line_capacity(self)
    __swig_destroy__ = _TaylorPLib.delete_Line
    __del__ = lambda self : None;
Line_swigregister = _TaylorPLib.Line_swigregister
Line_swigregister(Line)

class Line2(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Line2, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Line2, name)
    __repr__ = _swig_repr
    def iterator(self): return _TaylorPLib.Line2_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _TaylorPLib.Line2___nonzero__(self)
    def __bool__(self): return _TaylorPLib.Line2___bool__(self)
    def __len__(self): return _TaylorPLib.Line2___len__(self)
    def pop(self): return _TaylorPLib.Line2_pop(self)
    def __getslice__(self, *args): return _TaylorPLib.Line2___getslice__(self, *args)
    def __setslice__(self, *args): return _TaylorPLib.Line2___setslice__(self, *args)
    def __delslice__(self, *args): return _TaylorPLib.Line2___delslice__(self, *args)
    def __delitem__(self, *args): return _TaylorPLib.Line2___delitem__(self, *args)
    def __getitem__(self, *args): return _TaylorPLib.Line2___getitem__(self, *args)
    def __setitem__(self, *args): return _TaylorPLib.Line2___setitem__(self, *args)
    def append(self, *args): return _TaylorPLib.Line2_append(self, *args)
    def empty(self): return _TaylorPLib.Line2_empty(self)
    def size(self): return _TaylorPLib.Line2_size(self)
    def clear(self): return _TaylorPLib.Line2_clear(self)
    def swap(self, *args): return _TaylorPLib.Line2_swap(self, *args)
    def get_allocator(self): return _TaylorPLib.Line2_get_allocator(self)
    def begin(self): return _TaylorPLib.Line2_begin(self)
    def end(self): return _TaylorPLib.Line2_end(self)
    def rbegin(self): return _TaylorPLib.Line2_rbegin(self)
    def rend(self): return _TaylorPLib.Line2_rend(self)
    def pop_back(self): return _TaylorPLib.Line2_pop_back(self)
    def erase(self, *args): return _TaylorPLib.Line2_erase(self, *args)
    def __init__(self, *args): 
        this = _TaylorPLib.new_Line2(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _TaylorPLib.Line2_push_back(self, *args)
    def front(self): return _TaylorPLib.Line2_front(self)
    def back(self): return _TaylorPLib.Line2_back(self)
    def assign(self, *args): return _TaylorPLib.Line2_assign(self, *args)
    def resize(self, *args): return _TaylorPLib.Line2_resize(self, *args)
    def insert(self, *args): return _TaylorPLib.Line2_insert(self, *args)
    def reserve(self, *args): return _TaylorPLib.Line2_reserve(self, *args)
    def capacity(self): return _TaylorPLib.Line2_capacity(self)
    __swig_destroy__ = _TaylorPLib.delete_Line2
    __del__ = lambda self : None;
Line2_swigregister = _TaylorPLib.Line2_swigregister
Line2_swigregister(Line2)

class Array(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Array, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Array, name)
    __repr__ = _swig_repr
    def iterator(self): return _TaylorPLib.Array_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _TaylorPLib.Array___nonzero__(self)
    def __bool__(self): return _TaylorPLib.Array___bool__(self)
    def __len__(self): return _TaylorPLib.Array___len__(self)
    def pop(self): return _TaylorPLib.Array_pop(self)
    def __getslice__(self, *args): return _TaylorPLib.Array___getslice__(self, *args)
    def __setslice__(self, *args): return _TaylorPLib.Array___setslice__(self, *args)
    def __delslice__(self, *args): return _TaylorPLib.Array___delslice__(self, *args)
    def __delitem__(self, *args): return _TaylorPLib.Array___delitem__(self, *args)
    def __getitem__(self, *args): return _TaylorPLib.Array___getitem__(self, *args)
    def __setitem__(self, *args): return _TaylorPLib.Array___setitem__(self, *args)
    def append(self, *args): return _TaylorPLib.Array_append(self, *args)
    def empty(self): return _TaylorPLib.Array_empty(self)
    def size(self): return _TaylorPLib.Array_size(self)
    def clear(self): return _TaylorPLib.Array_clear(self)
    def swap(self, *args): return _TaylorPLib.Array_swap(self, *args)
    def get_allocator(self): return _TaylorPLib.Array_get_allocator(self)
    def begin(self): return _TaylorPLib.Array_begin(self)
    def end(self): return _TaylorPLib.Array_end(self)
    def rbegin(self): return _TaylorPLib.Array_rbegin(self)
    def rend(self): return _TaylorPLib.Array_rend(self)
    def pop_back(self): return _TaylorPLib.Array_pop_back(self)
    def erase(self, *args): return _TaylorPLib.Array_erase(self, *args)
    def __init__(self, *args): 
        this = _TaylorPLib.new_Array(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _TaylorPLib.Array_push_back(self, *args)
    def front(self): return _TaylorPLib.Array_front(self)
    def back(self): return _TaylorPLib.Array_back(self)
    def assign(self, *args): return _TaylorPLib.Array_assign(self, *args)
    def resize(self, *args): return _TaylorPLib.Array_resize(self, *args)
    def insert(self, *args): return _TaylorPLib.Array_insert(self, *args)
    def reserve(self, *args): return _TaylorPLib.Array_reserve(self, *args)
    def capacity(self): return _TaylorPLib.Array_capacity(self)
    __swig_destroy__ = _TaylorPLib.delete_Array
    __del__ = lambda self : None;
Array_swigregister = _TaylorPLib.Array_swigregister
Array_swigregister(Array)

MAX_MESSAGE_SIZE = _TaylorPLib.MAX_MESSAGE_SIZE
class Polynomial(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Polynomial, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Polynomial, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _TaylorPLib.new_Polynomial(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _TaylorPLib.delete_Polynomial
    __del__ = lambda self : None;
    def order(self): return _TaylorPLib.Polynomial_order(self)
    def ncoeff(self): return _TaylorPLib.Polynomial_ncoeff(self)
    def get(self, *args): return _TaylorPLib.Polynomial_get(self, *args)
    def __eq__(self, *args): return _TaylorPLib.Polynomial___eq__(self, *args)
    def __ne__(self, *args): return _TaylorPLib.Polynomial___ne__(self, *args)
    def __lt__(self, *args): return _TaylorPLib.Polynomial___lt__(self, *args)
    def __le__(self, *args): return _TaylorPLib.Polynomial___le__(self, *args)
    def __gt__(self, *args): return _TaylorPLib.Polynomial___gt__(self, *args)
    def __ge__(self, *args): return _TaylorPLib.Polynomial___ge__(self, *args)
    def __add__(self, *args): return _TaylorPLib.Polynomial___add__(self, *args)
    def __iadd__(self, *args): return _TaylorPLib.Polynomial___iadd__(self, *args)
    def __neg__(self): return _TaylorPLib.Polynomial___neg__(self)
    def __sub__(self, *args): return _TaylorPLib.Polynomial___sub__(self, *args)
    def __isub__(self, *args): return _TaylorPLib.Polynomial___isub__(self, *args)
    def __mul__(self, *args): return _TaylorPLib.Polynomial___mul__(self, *args)
    def __imul__(self, *args): return _TaylorPLib.Polynomial___imul__(self, *args)
    def __div__(self, *args): return _TaylorPLib.Polynomial___div__(self, *args)
    def __idiv__(self, *args): return _TaylorPLib.Polynomial___idiv__(self, *args)
    def sqr(self): return _TaylorPLib.Polynomial_sqr(self)
    def setSqr(self): return _TaylorPLib.Polynomial_setSqr(self)
    def sqrt(self): return _TaylorPLib.Polynomial_sqrt(self)
    def setSqrt(self): return _TaylorPLib.Polynomial_setSqrt(self)
    def _print(self, *args): return _TaylorPLib.Polynomial__print(self, *args)
    def eval(self, *args): return _TaylorPLib.Polynomial_eval(self, *args)
    def feval(self): return _TaylorPLib.Polynomial_feval(self)
    def shift(self): return _TaylorPLib.Polynomial_shift(self)
    def isConst(self, *args): return _TaylorPLib.Polynomial_isConst(self, *args)
    def isId(self, *args): return _TaylorPLib.Polynomial_isId(self, *args)
    def isZero(self, *args): return _TaylorPLib.Polynomial_isZero(self, *args)
    def set2Const(self, *args): return _TaylorPLib.Polynomial_set2Const(self, *args)
    def set2Id(self): return _TaylorPLib.Polynomial_set2Id(self)
    def set2Zero(self, *args): return _TaylorPLib.Polynomial_set2Zero(self, *args)
    def setCoeffs(self, *args): return _TaylorPLib.Polynomial_setCoeffs(self, *args)
    def __getitem__(self, *args): return _TaylorPLib.Polynomial___getitem__(self, *args)
    def __setitem__(self, *args): return _TaylorPLib.Polynomial___setitem__(self, *args)
    def __str__(self): return _TaylorPLib.Polynomial___str__(self)
Polynomial_swigregister = _TaylorPLib.Polynomial_swigregister
Polynomial_swigregister(Polynomial)

class Matrix(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Matrix, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Matrix, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _TaylorPLib.new_Matrix(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _TaylorPLib.delete_Matrix
    __del__ = lambda self : None;
    def nrows(self): return _TaylorPLib.Matrix_nrows(self)
    def ncols(self): return _TaylorPLib.Matrix_ncols(self)
    def dimT(self): return _TaylorPLib.Matrix_dimT(self)
    def get(self, *args): return _TaylorPLib.Matrix_get(self, *args)
    def set(self, *args): return _TaylorPLib.Matrix_set(self, *args)
    def __call__(self, *args): return _TaylorPLib.Matrix___call__(self, *args)
    def __eq__(self, *args): return _TaylorPLib.Matrix___eq__(self, *args)
    def __ne__(self, *args): return _TaylorPLib.Matrix___ne__(self, *args)
    def __add__(self, *args): return _TaylorPLib.Matrix___add__(self, *args)
    def __iadd__(self, *args): return _TaylorPLib.Matrix___iadd__(self, *args)
    def __sub__(self, *args): return _TaylorPLib.Matrix___sub__(self, *args)
    def __isub__(self, *args): return _TaylorPLib.Matrix___isub__(self, *args)
    def __neg__(self): return _TaylorPLib.Matrix___neg__(self)
    def __imul__(self, *args): return _TaylorPLib.Matrix___imul__(self, *args)
    def __mul__(self, *args): return _TaylorPLib.Matrix___mul__(self, *args)
    def mmCaABbC(self, *args): return _TaylorPLib.Matrix_mmCaABbC(self, *args)
    def bmmCaABbC(self, *args): return _TaylorPLib.Matrix_bmmCaABbC(self, *args)
    def mmCasABbC(self, *args): return _TaylorPLib.Matrix_mmCasABbC(self, *args)
    def mmCaAsBbC(self, *args): return _TaylorPLib.Matrix_mmCaAsBbC(self, *args)
    def mmCaAUTBPbC(self, *args): return _TaylorPLib.Matrix_mmCaAUTBPbC(self, *args)
    def mmCaAATbC(self, *args): return _TaylorPLib.Matrix_mmCaAATbC(self, *args)
    def mmCaATAbC(self, *args): return _TaylorPLib.Matrix_mmCaATAbC(self, *args)
    def mmCaATBbC(self, *args): return _TaylorPLib.Matrix_mmCaATBbC(self, *args)
    def mmCaATBPbC(self, *args): return _TaylorPLib.Matrix_mmCaATBPbC(self, *args)
    def mmCaABTbC(self, *args): return _TaylorPLib.Matrix_mmCaABTbC(self, *args)
    def bmmCaABTbC(self, *args): return _TaylorPLib.Matrix_bmmCaABTbC(self, *args)
    def mmCaIBbC(self, *args): return _TaylorPLib.Matrix_mmCaIBbC(self, *args)
    def mmCaAIbC(self, *args): return _TaylorPLib.Matrix_mmCaAIbC(self, *args)
    def cpermutem(self, *args): return _TaylorPLib.Matrix_cpermutem(self, *args)
    def rpermutem(self, *args): return _TaylorPLib.Matrix_rpermutem(self, *args)
    def transpose(self): return _TaylorPLib.Matrix_transpose(self)
    def asTranspose(self): return _TaylorPLib.Matrix_asTranspose(self)
    def shift(self): return _TaylorPLib.Matrix_shift(self)
    def isId(self): return _TaylorPLib.Matrix_isId(self)
    def isZero(self): return _TaylorPLib.Matrix_isZero(self)
    def set2Id(self, *args): return _TaylorPLib.Matrix_set2Id(self, *args)
    def set2IdFromIndices(self, *args): return _TaylorPLib.Matrix_set2IdFromIndices(self, *args)
    def set2Zero(self, *args): return _TaylorPLib.Matrix_set2Zero(self, *args)
    def set2ZeroFromIndices(self, *args): return _TaylorPLib.Matrix_set2ZeroFromIndices(self, *args)
    def set2Val(self, *args): return _TaylorPLib.Matrix_set2Val(self, *args)
    def set2ValFromIndices(self, *args): return _TaylorPLib.Matrix_set2ValFromIndices(self, *args)
    def _print(self, *args): return _TaylorPLib.Matrix__print(self, *args)
    def __getitem__(self, *args): return _TaylorPLib.Matrix___getitem__(self, *args)
    def __setitem__(self, *args): return _TaylorPLib.Matrix___setitem__(self, *args)
    def __str__(self): return _TaylorPLib.Matrix___str__(self)
Matrix_swigregister = _TaylorPLib.Matrix_swigregister
Matrix_swigregister(Matrix)

class MathException(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, MathException, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, MathException, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _TaylorPLib.new_MathException(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _TaylorPLib.delete_MathException
    __del__ = lambda self : None;
    def what(self): return _TaylorPLib.MathException_what(self)
MathException_swigregister = _TaylorPLib.MathException_swigregister
MathException_swigregister(MathException)

# This file is compatible with both classic and new-style classes.


